//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1.Ass2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Heuristic1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ass2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
        
        string EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        App1.Ass2.CompositeType GetDataUsingDataContract(App1.Ass2.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(App1.Ass2.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        App1.Ass2.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Heuristicout", ReplyAction="http://tempuri.org/IService1/HeuristicoutResponse")]
        string Heuristicout(string instr);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Heuristicout", ReplyAction="http://tempuri.org/IService1/HeuristicoutResponse")]
        System.IAsyncResult BeginHeuristicout(string instr, System.AsyncCallback callback, object asyncState);
        
        string EndHeuristicout(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Greedyout", ReplyAction="http://tempuri.org/IService1/GreedyoutResponse")]
        string Greedyout(string instr);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Greedyout", ReplyAction="http://tempuri.org/IService1/GreedyoutResponse")]
        System.IAsyncResult BeginGreedyout(string instr, System.AsyncCallback callback, object asyncState);
        
        string EndGreedyout(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Heuristicout2", ReplyAction="http://tempuri.org/IService1/Heuristicout2Response")]
        string Heuristicout2(string instr);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Heuristicout2", ReplyAction="http://tempuri.org/IService1/Heuristicout2Response")]
        System.IAsyncResult BeginHeuristicout2(string instr, System.AsyncCallback callback, object asyncState);
        
        string EndHeuristicout2(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : App1.Ass2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public App1.Ass2.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((App1.Ass2.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeuristicoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HeuristicoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreedyoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GreedyoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Heuristicout2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Heuristicout2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<App1.Ass2.IService1>, App1.Ass2.IService1 {
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
        
        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
        
        private BeginOperationDelegate onBeginHeuristicoutDelegate;
        
        private EndOperationDelegate onEndHeuristicoutDelegate;
        
        private System.Threading.SendOrPostCallback onHeuristicoutCompletedDelegate;
        
        private BeginOperationDelegate onBeginGreedyoutDelegate;
        
        private EndOperationDelegate onEndGreedyoutDelegate;
        
        private System.Threading.SendOrPostCallback onGreedyoutCompletedDelegate;
        
        private BeginOperationDelegate onBeginHeuristicout2Delegate;
        
        private EndOperationDelegate onEndHeuristicout2Delegate;
        
        private System.Threading.SendOrPostCallback onHeuristicout2CompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
        
        public event System.EventHandler<HeuristicoutCompletedEventArgs> HeuristicoutCompleted;
        
        public event System.EventHandler<GreedyoutCompletedEventArgs> GreedyoutCompleted;
        
        public event System.EventHandler<Heuristicout2CompletedEventArgs> Heuristicout2Completed;
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int value = ((int)(inValues[0]));
            return this.BeginGetData(value, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            string retVal = this.EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        public void GetDataAsync(int value, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        public App1.Ass2.CompositeType GetDataUsingDataContract(App1.Ass2.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDataUsingDataContract(App1.Ass2.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public App1.Ass2.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result) {
            return base.Channel.EndGetDataUsingDataContract(result);
        }
        
        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState) {
            App1.Ass2.CompositeType composite = ((App1.Ass2.CompositeType)(inValues[0]));
            return this.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result) {
            App1.Ass2.CompositeType retVal = this.EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataUsingDataContractCompleted(object state) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataUsingDataContractAsync(App1.Ass2.CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        public void GetDataUsingDataContractAsync(App1.Ass2.CompositeType composite, object userState) {
            if ((this.onBeginGetDataUsingDataContractDelegate == null)) {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null)) {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null)) {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }
        
        public string Heuristicout(string instr) {
            return base.Channel.Heuristicout(instr);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHeuristicout(string instr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHeuristicout(instr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHeuristicout(System.IAsyncResult result) {
            return base.Channel.EndHeuristicout(result);
        }
        
        private System.IAsyncResult OnBeginHeuristicout(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string instr = ((string)(inValues[0]));
            return this.BeginHeuristicout(instr, callback, asyncState);
        }
        
        private object[] OnEndHeuristicout(System.IAsyncResult result) {
            string retVal = this.EndHeuristicout(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHeuristicoutCompleted(object state) {
            if ((this.HeuristicoutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HeuristicoutCompleted(this, new HeuristicoutCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HeuristicoutAsync(string instr) {
            this.HeuristicoutAsync(instr, null);
        }
        
        public void HeuristicoutAsync(string instr, object userState) {
            if ((this.onBeginHeuristicoutDelegate == null)) {
                this.onBeginHeuristicoutDelegate = new BeginOperationDelegate(this.OnBeginHeuristicout);
            }
            if ((this.onEndHeuristicoutDelegate == null)) {
                this.onEndHeuristicoutDelegate = new EndOperationDelegate(this.OnEndHeuristicout);
            }
            if ((this.onHeuristicoutCompletedDelegate == null)) {
                this.onHeuristicoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHeuristicoutCompleted);
            }
            base.InvokeAsync(this.onBeginHeuristicoutDelegate, new object[] {
                        instr}, this.onEndHeuristicoutDelegate, this.onHeuristicoutCompletedDelegate, userState);
        }
        
        public string Greedyout(string instr) {
            return base.Channel.Greedyout(instr);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGreedyout(string instr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGreedyout(instr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGreedyout(System.IAsyncResult result) {
            return base.Channel.EndGreedyout(result);
        }
        
        private System.IAsyncResult OnBeginGreedyout(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string instr = ((string)(inValues[0]));
            return this.BeginGreedyout(instr, callback, asyncState);
        }
        
        private object[] OnEndGreedyout(System.IAsyncResult result) {
            string retVal = this.EndGreedyout(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGreedyoutCompleted(object state) {
            if ((this.GreedyoutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GreedyoutCompleted(this, new GreedyoutCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GreedyoutAsync(string instr) {
            this.GreedyoutAsync(instr, null);
        }
        
        public void GreedyoutAsync(string instr, object userState) {
            if ((this.onBeginGreedyoutDelegate == null)) {
                this.onBeginGreedyoutDelegate = new BeginOperationDelegate(this.OnBeginGreedyout);
            }
            if ((this.onEndGreedyoutDelegate == null)) {
                this.onEndGreedyoutDelegate = new EndOperationDelegate(this.OnEndGreedyout);
            }
            if ((this.onGreedyoutCompletedDelegate == null)) {
                this.onGreedyoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGreedyoutCompleted);
            }
            base.InvokeAsync(this.onBeginGreedyoutDelegate, new object[] {
                        instr}, this.onEndGreedyoutDelegate, this.onGreedyoutCompletedDelegate, userState);
        }
        
        public string Heuristicout2(string instr) {
            return base.Channel.Heuristicout2(instr);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginHeuristicout2(string instr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHeuristicout2(instr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndHeuristicout2(System.IAsyncResult result) {
            return base.Channel.EndHeuristicout2(result);
        }
        
        private System.IAsyncResult OnBeginHeuristicout2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string instr = ((string)(inValues[0]));
            return this.BeginHeuristicout2(instr, callback, asyncState);
        }
        
        private object[] OnEndHeuristicout2(System.IAsyncResult result) {
            string retVal = this.EndHeuristicout2(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHeuristicout2Completed(object state) {
            if ((this.Heuristicout2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Heuristicout2Completed(this, new Heuristicout2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Heuristicout2Async(string instr) {
            this.Heuristicout2Async(instr, null);
        }
        
        public void Heuristicout2Async(string instr, object userState) {
            if ((this.onBeginHeuristicout2Delegate == null)) {
                this.onBeginHeuristicout2Delegate = new BeginOperationDelegate(this.OnBeginHeuristicout2);
            }
            if ((this.onEndHeuristicout2Delegate == null)) {
                this.onEndHeuristicout2Delegate = new EndOperationDelegate(this.OnEndHeuristicout2);
            }
            if ((this.onHeuristicout2CompletedDelegate == null)) {
                this.onHeuristicout2CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHeuristicout2Completed);
            }
            base.InvokeAsync(this.onBeginHeuristicout2Delegate, new object[] {
                        instr}, this.onEndHeuristicout2Delegate, this.onHeuristicout2CompletedDelegate, userState);
        }
    }
}
